apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
  namespace: hello-gb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-nginx
  template:
    metadata:
      labels:
        app: hello-world-nginx
    spec:
      containers:
      - name: nginx
        image: gburucua/hello-image:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: html
        hostPath:
          path: /usr/share/nginx/html/index.html
