apiVersion: v1
kind: PersistentVolume
metadata:
  name: index-html-pv
  namespace: ingress-nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/index2.html
    type: File