apiVersion: v1
kind: PersistentVolume
metadata:
  name: index-html-pv
  namespace: hello-gb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/host/index2.html